/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotesRouteImport } from './routes/votes'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapCoreDotxmlRouteImport } from './routes/sitemap-core[.]xml'
import { Route as SitemapAssetsDotxmlRouteImport } from './routes/sitemap-assets[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrowseRouteImport } from './routes/_browse'
import { Route as BrowseIndexRouteImport } from './routes/_browse.index'
import { Route as VoteIdRouteImport } from './routes/vote.$id'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as BrowseGamesSlugRouteImport } from './routes/_browse.games.$slug'
import { Route as BrowseGamesSlugCategoryRouteImport } from './routes/_browse.games.$slug_.$category'

const VotesRoute = VotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCoreDotxmlRoute = SitemapCoreDotxmlRouteImport.update({
  id: '/sitemap-core.xml',
  path: '/sitemap-core.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapAssetsDotxmlRoute = SitemapAssetsDotxmlRouteImport.update({
  id: '/sitemap-assets.xml',
  path: '/sitemap-assets.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/_browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseRoute,
} as any)
const VoteIdRoute = VoteIdRouteImport.update({
  id: '/vote/$id',
  path: '/vote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseGamesSlugRoute = BrowseGamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseGamesSlugCategoryRoute = BrowseGamesSlugCategoryRouteImport.update({
  id: '/games/$slug_/$category',
  path: '/games/$slug/$category',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BrowseIndexRoute
  '/changelog': typeof ChangelogRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/requests': typeof RequestsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sitemap-assets.xml': typeof SitemapAssetsDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uploads': typeof UploadsRoute
  '/votes': typeof VotesRoute
  '/asset/$id': typeof AssetIdRoute
  '/request/$id': typeof RequestIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/games/$slug': typeof BrowseGamesSlugRoute
  '/games/$slug/$category': typeof BrowseGamesSlugCategoryRoute
}
export interface FileRoutesByTo {
  '/changelog': typeof ChangelogRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/requests': typeof RequestsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sitemap-assets.xml': typeof SitemapAssetsDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uploads': typeof UploadsRoute
  '/votes': typeof VotesRoute
  '/asset/$id': typeof AssetIdRoute
  '/request/$id': typeof RequestIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/': typeof BrowseIndexRoute
  '/games/$slug': typeof BrowseGamesSlugRoute
  '/games/$slug/$category': typeof BrowseGamesSlugCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_browse': typeof BrowseRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contributors': typeof ContributorsRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/requests': typeof RequestsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/sitemap-assets.xml': typeof SitemapAssetsDotxmlRoute
  '/sitemap-core.xml': typeof SitemapCoreDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uploads': typeof UploadsRoute
  '/votes': typeof VotesRoute
  '/asset/$id': typeof AssetIdRoute
  '/request/$id': typeof RequestIdRoute
  '/vote/$id': typeof VoteIdRoute
  '/_browse/': typeof BrowseIndexRoute
  '/_browse/games/$slug': typeof BrowseGamesSlugRoute
  '/_browse/games/$slug_/$category': typeof BrowseGamesSlugCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/contributors'
    | '/dashboard'
    | '/downloads'
    | '/faq'
    | '/games'
    | '/requests'
    | '/saved'
    | '/settings'
    | '/sitemap-assets.xml'
    | '/sitemap-core.xml'
    | '/sitemap.xml'
    | '/uploads'
    | '/votes'
    | '/asset/$id'
    | '/request/$id'
    | '/vote/$id'
    | '/games/$slug'
    | '/games/$slug/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/changelog'
    | '/contributors'
    | '/dashboard'
    | '/downloads'
    | '/faq'
    | '/games'
    | '/requests'
    | '/saved'
    | '/settings'
    | '/sitemap-assets.xml'
    | '/sitemap-core.xml'
    | '/sitemap.xml'
    | '/uploads'
    | '/votes'
    | '/asset/$id'
    | '/request/$id'
    | '/vote/$id'
    | '/'
    | '/games/$slug'
    | '/games/$slug/$category'
  id:
    | '__root__'
    | '/_browse'
    | '/changelog'
    | '/contributors'
    | '/dashboard'
    | '/downloads'
    | '/faq'
    | '/games'
    | '/requests'
    | '/saved'
    | '/settings'
    | '/sitemap-assets.xml'
    | '/sitemap-core.xml'
    | '/sitemap.xml'
    | '/uploads'
    | '/votes'
    | '/asset/$id'
    | '/request/$id'
    | '/vote/$id'
    | '/_browse/'
    | '/_browse/games/$slug'
    | '/_browse/games/$slug_/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BrowseRoute: typeof BrowseRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContributorsRoute: typeof ContributorsRoute
  DashboardRoute: typeof DashboardRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  RequestsRoute: typeof RequestsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SitemapAssetsDotxmlRoute: typeof SitemapAssetsDotxmlRoute
  SitemapCoreDotxmlRoute: typeof SitemapCoreDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadsRoute: typeof UploadsRoute
  VotesRoute: typeof VotesRoute
  AssetIdRoute: typeof AssetIdRoute
  RequestIdRoute: typeof RequestIdRoute
  VoteIdRoute: typeof VoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/votes': {
      id: '/votes'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-core.xml': {
      id: '/sitemap-core.xml'
      path: '/sitemap-core.xml'
      fullPath: '/sitemap-core.xml'
      preLoaderRoute: typeof SitemapCoreDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-assets.xml': {
      id: '/sitemap-assets.xml'
      path: '/sitemap-assets.xml'
      fullPath: '/sitemap-assets.xml'
      preLoaderRoute: typeof SitemapAssetsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse': {
      id: '/_browse'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/': {
      id: '/_browse/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/vote/$id': {
      id: '/vote/$id'
      path: '/vote/$id'
      fullPath: '/vote/$id'
      preLoaderRoute: typeof VoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/games/$slug': {
      id: '/_browse/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof BrowseGamesSlugRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/games/$slug_/$category': {
      id: '/_browse/games/$slug_/$category'
      path: '/games/$slug/$category'
      fullPath: '/games/$slug/$category'
      preLoaderRoute: typeof BrowseGamesSlugCategoryRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseIndexRoute: typeof BrowseIndexRoute
  BrowseGamesSlugRoute: typeof BrowseGamesSlugRoute
  BrowseGamesSlugCategoryRoute: typeof BrowseGamesSlugCategoryRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseIndexRoute: BrowseIndexRoute,
  BrowseGamesSlugRoute: BrowseGamesSlugRoute,
  BrowseGamesSlugCategoryRoute: BrowseGamesSlugCategoryRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BrowseRoute: BrowseRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContributorsRoute: ContributorsRoute,
  DashboardRoute: DashboardRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  RequestsRoute: RequestsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SitemapAssetsDotxmlRoute: SitemapAssetsDotxmlRoute,
  SitemapCoreDotxmlRoute: SitemapCoreDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadsRoute: UploadsRoute,
  VotesRoute: VotesRoute,
  AssetIdRoute: AssetIdRoute,
  RequestIdRoute: RequestIdRoute,
  VoteIdRoute: VoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
